version: 2
jobs:
  build:
    working_directory: ~/reg-suit
    docker:
      - image: node:6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Bootstrap packages
          command: yarn run lerna -- bootstrap
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Test
          command: yarn run test
  deploy:
    working_directory: ~/reg-suit
    docker:
      - image: node:6
    steps:
      - run:
          name: deploy-service
          command: ls -la

workflows:
  version: 2
  publish_npm:
    jobs:
      - build
      - hold:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - hold

