defaults: &defaults
  working_directory: ~/temp
  docker:
    - image: node:6

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - run:
          command: |
            mkdir -p reg-suit
            cd reg-suit
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Bootstrap packages
          command: yarn run lerna -- bootstrap
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Test
          command: yarn run test
      - run:
          command: cd ../
      - persist_to_workspace:
          root: reg-suit
          paths:
            - packages
            - node_modules
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
        at: ~/temp/reg-suit
      - run:
          name: deploy-service
          command: ls -la

workflows:
  version: 2
  publish_npm:
    jobs:
      - build
      - hold:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - hold

