version: 2
jobs:
  build:
    working_directory: ~/reg-suit
    docker:
      - image: node:6

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Bootstrap packages
          command: yarn run lerna -- bootstrap
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Test
          command: yarn run test

